environment:
  packageVersion: 0.1.0

init:
 - ps: $env.pre_release = Get-Date -Format "yyyyMMdd-HHmmss"
 - ps: $env:assembly_version = "$env:packageVersion.0"
 - ps: $env:assembly_file_version = "$env:packageVersion.$env:appveyor_build_number"
 - ps: $env:assembly_informational_version = "$env:packageVersion-pre-$env:pre_release"
 - ps: $env:my_version="0.1"

# configuration for all branches starting from "dev-"
# build in Debug mode and deploy locally for testing
-
    branches:
    except:
      - master
      assembly_info:
        patch: true
        file: '**\AssemblyInfo.*'
        assembly_version: '$env:my_version.0.0'
        assembly_file_version: '$env:my_version.0.{build}'
        assembly_informational_version:  '$env:my_version-pre$env:pre_release'
      configuration: Release
      build:
        #publish_nuget: true
        #publish_nuget_symbols: true
      verbosity: minimal
      artifacts:
        - path: '**\AssemblyInfo.*'
        name: AssemblyInfos
        type: zip

# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master
    assembly_info:
      patch: true
      file: '**\AssemblyInfo.*'
      assembly_version: '$env:my_version.0.0'
      assembly_file_version: '$env:my_version.0.{build}'
      assembly_informational_version: '$env:my_version.0.{build}'
    configuration: Release
    build:
        #publish_nuget: true
        #publish_nuget_symbols: true
     verbosity: minimal

#after_build:
#- ps:
#deploy:
#- provider: NuGet
#  api_key:
#    secure: U0b7CQk3G8x+xfzoeGz3o26PyoR4G/DuuJ/G63mMrj+mgrDgV0/JA7/4fqqzO2eH
#  on:
#    branch: master
