- 
  init:
    - ps: $env:my_version=0.1
    - ps: $pre_release = Get-Date -Format "yyyymmdd-hhmmss"
  version: $env:my_version.{build}  
  branches:
    except:
      - master
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$env:my_version.0.0'
    assembly_file_version: '$env:my_version.0.{build}'
    assembly_informational_version: '$env:my_version.{build}.pre-$pre_release'
  configuration: Release
  build:
    #publish_nuget: true
    #publish_nuget_symbols: true
    verbosity: minimal
  artifacts:
  - path: '**\AssemblyInfo.*'
    name: AssemblyInfos
    type: zip
-
  init:
    - ps: $env:my_version=0.1
  version: $env:my_version.{build}
  branches:
    only:
      - master
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$env:my_version.0.0'
    assembly_file_version: '$env:my_version.0.{build}'
    assembly_informational_version: '{assembly_file_version}'
  configuration: Release
  build:
    #publish_nuget: true
    #publish_nuget_symbols: true
    verbosity: minimal
  
#after_build:
#- ps: 
#deploy:
#- provider: NuGet
#  api_key:
#    secure: U0b7CQk3G8x+xfzoeGz3o26PyoR4G/DuuJ/G63mMrj+mgrDgV0/JA7/4fqqzO2eH
#  on:
#    branch: master
