-
  init:
    - ps: $pre_release = Get-Date -Format "yyyymmdd-hhmmss"
  major_minor: '0.1'
  version: '{major_minor}.{build}'
  appveyor_repo_tag: true
  assembly_informational_version: '{assembly_file_version}'
-
  branches:
    except:
      - master
  assembly_file_version: '{major_minor}.0.{build}'
  assembly_informational_version: '{version}.pre-{pre_release}'
-
  configuration: Release
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{major_minor}.0.0'
    assembly_file_version: '{assembly_file_version}'
    assembly_informational_version: '{assembly_informational_version}'
  build:
    #publish_nuget: true
    #publish_nuget_symbols: true
    verbosity: minimal
#after_build:
#- ps: 
#deploy:
#- provider: NuGet
#  api_key:
#    secure: U0b7CQk3G8x+xfzoeGz3o26PyoR4G/DuuJ/G63mMrj+mgrDgV0/JA7/4fqqzO2eH
#  on:
#    branch: master